services:
  db:
    image: mysql:8.0
    container_name: hr_db_server
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=hrproject
      - MYSQL_DATABASE=hr_database
      - MYSQL_USER=hr_admin
      - MYSQL_PASSWORD=hr_admin
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      #Initialization scripts
      - ./db-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 3

  backend:
    build:
      context: ./services
      dockerfile: Dockerfile
    container_name: hr_back_server
    ports:
      - "8090:8090"
    environment:
      - MICRONAUT_SERVER_PORT=8090
      - DATASOURCES_DEFAULT_URL=jdbc:mysql://db:3306/hr_database?allowPublicKeyRetrieval=true&useSSL=false
      - DATASOURCES_DEFAULT_USERNAME=hr_admin
      - DATASOURCES_DEFAULT_PASSWORD=hr_admin
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./Front
      dockerfile: Dockerfile
    container_name: hr_front_server
    ports:
      - "8080:8080"
    depends_on:
      - backend

volumes:
  mysql_data:
